# Generated by Django 3.2 on 2021-05-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210515_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_rental_cart',
            new_name='original_cart_rental',
        ),
    ]
