# Generated by Django 3.2 on 2021-05-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrentalitem',
            name='item_returned',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
