# Generated by Django 3.2 on 2021-05-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderrentalitem_item_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrentalitem',
            name='item_returned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
